name = "Log Server"
author = "log090519"
version = "0.13.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "35e689f9158c2d5e4b75d3df1e4ca45230be90375efbfc8a2743a754cefc780d"

[versions]
minecraft = "26.2"
fabric = "0.19.5"
