name = "Log Server"
author = "log090519"
version = "0.5.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a45aba2187e24622059d7b8784b7ca43dca43a69d8ad5a750dae439c4b93f06f"

[versions]
minecraft = "26.2"
fabric = "0.19.5"
